version: '3.6'

services:
  mazeconsumer:
    container_name: mazeconsumer
    image: ${DOCKER_REGISTRY-}mazeconsumer
    build:
      context: .
      dockerfile: MazeConsumer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - IndexingServiceUrl=http://indexingservice/
      - NumberOfThread=1
    ports:
      - "8000:80"
    networks:
      - vlan
    depends_on:
      - logs
      - indexingservice
    volumes:
      - ./data:/data

  tvshows:
    container_name: tvshows
    image: ${DOCKER_REGISTRY-}tvshows
    build:
      context: .
      dockerfile: TvShows/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - FingerPrint=3dd5cc4581083b516fb8cbd3b7585aba303e5ab047f90044c5d5781f064a6019
      - EsPassword=66NFren91Z4vDrgdkEOW
      - EsUsername=elastic
      - ElasticClientUrl=https://es01:9200
    ports:
      - "8001:80"
    networks:
      - vlan
    depends_on:
      - logs
  
  indexingservice:
    container_name: indexingservice
    image: ${DOCKER_REGISTRY-}indexingservice
    build:
      context: .
      dockerfile: IndexingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - FingerPrint=3dd5cc4581083b516fb8cbd3b7585aba303e5ab047f90044c5d5781f064a6019
      - EsPassword=66NFren91Z4vDrgdkEOW
      - EsUsername=elastic
      - ElasticClientUrl=https://es01:9200
    volumes:
      - ./data:/data
    ports:
      - "8002:80"
    networks:
      - vlan
    depends_on:
      - logs
      
  logs:
    image: datalust/seq:latest
    container_name: logs
    deploy:
      resources:
        limits:
          memory: 300M
    environment:
      - ACCEPT_EULA=Y
    networks:
      - vlan
    ports:
      - "8003:80"
      - "5341:5341"  

networks:
  vlan:
    external: true
  