version: '3.4'

services:
  mazeconsumer:
    container_name: mazeconsumer
    image: ${DOCKER_REGISTRY-}mazeconsumer
    build:
      context: .
      dockerfile: MazeConsumer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8000:80"
    networks:
      - vlan
    depends_on:
      - elasticsearch
      - logs
      - indexingservice

  tvshows:
    container_name: tvshows
    image: ${DOCKER_REGISTRY-}tvshows
    build:
      context: .
      dockerfile: TvShows/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8001:80"
    networks:
      - vlan
    depends_on:
      - elasticsearch
      - logs
  
  indexingservice:
    container_name: indexingservice
    image: ${DOCKER_REGISTRY-}indexingservice
    build:
      context: .
      dockerfile: IndexingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8002:80"
    networks:
      - vlan
    depends_on:
      - elasticsearch
      - logs
      
  logs:
    image: datalust/seq:latest
    container_name: logs
    deploy:
      resources:
        limits:
          memory: 300M
    volumes:
      - ./logs:/logs
    environment:
      - ACCEPT_EULA=Y
    networks:
      - vlan
    ports:
      - "8003:80"
      - "5341:5341"  

  elasticsearch:
     container_name: elasticsearch
     image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
     environment:
      #- node.name=elasticsearch
      #- cluster.name=es-docker-cluster
      #- discovery.type=single-node
      #- bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     #ulimits:
     # memlock:
     #   soft: -1
     #   hard: -1
     # nofile:
     #   soft: 65536
     #   hard: 65536
     #cap_add:
     # - IPC_LOCK
     ports:
        - "9200:9200"
#        - "9300:9300"
     #volumes:
     #   - ./esdata:/usr/share/elasticsearch/data
     networks:
        - vlan
  kibana:
     container_name: kibana   
     image: kibana:8.6.2
     environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
     ports:
         - "5601:5601"
     networks:
         - vlan
     depends_on:
         - elasticsearch
networks:
  vlan: