version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  mazeconsumer:
    container_name: mazeconsumer
    image: ${DOCKER_REGISTRY-}mazeconsumer
    build:
      context: .
      dockerfile: MazeConsumer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8000:80"
    networks:
      - vlan

  tvshows:
    container_name: tvshows
    image: ${DOCKER_REGISTRY-}tvshows
    build:
      context: .
      dockerfile: TvShows/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8001:80"
    networks:
      - vlan
  
  indexingservice:
    container_name: indexingservice
    image: ${DOCKER_REGISTRY-}indexingservice
    build:
      context: .
      dockerfile: IndexingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8002:80"
    networks:
      - vlan
      
  logs:
    image: datalust/seq:latest
    container_name: logs
    deploy:
      resources:
        limits:
          memory: 300M
    volumes:
      - ./logs:/logs
    environment:
      - ACCEPT_EULA=Y
    networks:
      - vlan
    ports:
      - "8003:80"
      - "5341:5341"  
  elasticsearch:
     container_name: elasticsearch
     image: elasticsearch:8.6.2
     ports:
        - "9200:9200"
        - "9300:9300"
     volumes:
        - ./esdata:/usr/share/elasticsearch/data
     networks:
        - vlan
  kibana:
     container_name: kibana   
     image: kibana:8.6.2
     ports:
         - "5601:5601"
     networks:
         - vlan
     depends_on:
         - elasticsearch
networks:
  vlan: